services:
  fastapi_server:
    container_name: ${PROJECT_NAME}_fastapi_server
    image: ghcr.io/risc-v-kernelci-mentorship/riscv-tuxsuite-api:latest
    restart: always
    command: "sh -c 'gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./log.ini:/log.ini
      - fastapi_riscv_database:/db
      - fastapi_riscv_logs:/logs
    expose:
      - 8000
    env_file: ".env"

  caddy_reverse_proxy:
    container_name: ${PROJECT_NAME}_caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: ".env_caddy"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  fastapi_riscv_database:
  fastapi_riscv_logs: